# .github/workflows/pull-request.yml
# Write better PRs and commit messages
name: "Word Weasel"
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
jobs:
  pr-weasel:
    runs-on: ubuntu-latest
    steps:
      - uses: codingjoe/word-weasel@main
        with:
          text: ${{ github.event.pull_request.title }} ${{ github.event.pull_request.body }}
